kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data
  - role: worker
    extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data
  - role: worker
    extraMounts:
    - hostPath: ./data
      containerPath: /tmp/data

# # Use Calico instead of kindnet 
# networking:
#   disableDefaultCNI: true # disable kindnet
#   podSubnet: "10.245.0.0/16"
#   serviceSubnet: "10.97.0.0/12"
# # Then apply the manifest of calico :
# # kubectl apply -f https://docs.projectcalico.org/latest/manifests/calico.yaml

# # Finally, test the network & network policy :
# # https://projectcalico.docs.tigera.io/getting-started/kubernetes/hardway/test-networking