output "ssh_private_key" {
  description = "ssh key generated by terraform"
  value       = tls_private_key.bastion_private_key.private_key_pem
}

output "public_ip" {
  value = aws_instance.bastion.public_ip
}

output "id" {
  value = aws_instance.bastion.id
}

# An alternative that avoids that is to save the pem file in AWS Secrets Manager, or encrypted in S3, and provide a command to fetch it & create local file.
resource "local_sensitive_file" "bastion_private_key" {
  filename        = pathexpand("~/.ssh/${var.bastion_key_name}.pem")
  file_permission = "400"
  content         = aws_secretsmanager_secret_version.bastion_private_key_secret_version.secret_string #tls_private_key.bastion_private_key.private_key_pem
}
