# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: listen-80
#   namespace: demo
# spec:
#   selector:
#     matchLabels:
#       app: listen-80
#   template:
#     metadata:
#       labels:
#         app: listen-80
#     spec:
#       containers:
#       - image: hashicorp/http-echo:0.2.3
#         name: listen-80
#         ports:
#         - name: http
#           containerPort: 5678
#           hostPort: 80

kind: Pod
apiVersion: v1
metadata:
  name: listen-80
  namespace: demo
  labels:
    app: listen-80
spec:
  containers:
    - name: listen-80
      image: hashicorp/http-echo:0.2.3
      ports:
        - name: http
          containerPort: 5678
          hostPort: 80
      args:
        - "-text=listen-80"
---